[format]
line-width = 100
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
assignment-style = "arrow"
exclude = ["packages/**/inst/tinytest/test-*.R"]
default-exclude = true
skip = []
table = []
default-table = true
